# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD Proccess mpp-admin.newus.id

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20]
    env:
      NEXT_PUBLIC_API_URL_MPP: https://backend-mpp.newus.id/api
      NEXT_PUBLIC_TINYMCE_API_KEY: phyaabbmzyqjnf46uyvziekqex174yrbufhte1wwvni8avg2
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name : Run NPM
      run: npm ci
    - name : Run build
      run: npm run build --if-present
  
